### ISSUE TITLE
Watched expressions are not expandable in debugger tool window

### ISSUE THREAD

**Issue by obiwan87** [obiwan87/odin-intellij#100]
> 
> All array-like types but it also applies to struct types in the case where the watch field is being used
> So if you were to add a watch for a value that can be expanded, it still won't expand but instead will just show the structure as text in the watch window
> The issue seems to be that types are not parsed as they usually are when evaluated in watch fields or the expression evaluator
> Normally a struct will be expandable when it's included in the locals and this works fine in the normal case, but when returned via the watch window or evaluator they will not undergo the same parsing and possible expansion
> Here is very brief example:
> 
> We can see that the info is parsed in the locals bit and we can expand to see each member
> When used as a watch value the same is not possible, even though it should be
> This same problem exists when you want to expand an array (which usually is not even possible to see in normal debug info), i.e.: array_values.data, 5. When we do this we only get the text back for the array expansion, which is congruent with the overarching issue of what comes back from VSDebug is not parsed (I think)

https://github.com/user-attachments/assets/874d813c-a9b5-49a1-b8b6-106f64243f0f

**Comment by GoNZooo** [comment]
Here is the array example more specifically:

We see that we have a slice with length 2, normally we would expand this to show both members with array_name, 2. What we get back is not expandable.

https://github.com/user-attachments/assets/6563882e-3327-4597-a7bc-2fc131eeade1
