### ISSUE TITLE
Symbols do not appear to populate on RustRover 2024.2

### ISSUE THREAD

**Issue by zydeas** [obiwan87/odin-intellij#102]
No symbols appear to be catalogued. I can use Go To Definition and autocomplete appears to work.

Using RustRover "Build #RR-242.21829.198, built on September 4, 2024"

![image](https://github.com/user-attachments/assets/b67748d9-c25c-4ec8-b352-d975dca3213d)

The project layout:
![image](https://github.com/user-attachments/assets/2a333d8a-d20d-42f1-9822-bc3b29011f06)

**Comment by obiwan87** [comment]
Hi, I answered you on the discord channel. But in case the message gets lost in the history. Symbol search is only supported in version >= 0.9.0. Can you please try to install it. You will find the binary in the discord chat and shortly it will also appear in the releases here on github.

**Comment by zydeas** [comment]
Sure! I'll get back to you when I do that.

**Comment by obiwan87** [comment]
@zydeas Hope it worked. Can I close this issue?

**Comment by zydeas** [comment]
Appears to have fixed it.
