### ISSUE TITLE
NullPointerException in populateBuiltinSymbols every time project is opened

### ISSUE THREAD

**Issue by jhcdjhcd** [obiwan87/odin-intellij#103]
Thanks for the plugin. Everything is working (debugging works) but every time I open my project in CLion I get an IDE error with this stack:

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at com.lasagnerd.odin.codeInsight.sdk.OdinSdkServiceBase.populateBuiltinSymbols(OdinSdkServiceBase.java:371)
	at com.lasagnerd.odin.codeInsight.sdk.OdinSdkServiceBase.loadBuiltinSymbols(OdinSdkServiceBase.java:144)
	at com.lasagnerd.odin.codeInsight.sdk.OdinSdkServiceImpl$1.lambda$run$0(OdinSdkServiceImpl.java:57)

Version 0.8.0, CLion is 2024.3.1.1

**Comment by obiwan87** [comment]
This might be a badly handled configuration error. Did you setup your SDK path in the odin project settings? If yes, can you please make sure the path contains both the executable and the directories core, base and vendor? 

Which Odin version are you using?

**Comment by jhcdjhcd** [comment]
OK it looks like this is fixed just by using the latest Odin. I've done some little tests here with a minimal 'hellope' project and it happens 100% on first opening the project in CLion with 'dev-2024-01-nightly:5961d4b3' but never happens with 'dev-2024-12-nightly:ad99d20'. Thanks for the quick response!

**Comment by obiwan87** [comment]
Ok, I imagined. I'll close the issue then

**Comment by meoyawn** [comment]
running into this as well

RustRover 2025.1.5
odin dev-2025-07:090cac62f
odin-intellij 0.13.0

to add it can't resolve stdlib imports, although the file runs perfectly fine
<img width="389" height="209" alt="Image" src="https://github.com/user-attachments/assets/6e8fb140-d151-49e9-99d1-9f21ebfe950c" />

**Comment by meoyawn** [comment]
please nevermind, deleting `.idea` fixed everything
