### ISSUE TITLE
Support for 2024.1 versions

### ISSUE THREAD

**Issue by sunarch** [obiwan87/odin-intellij#22]
Hi,

this is not a pressing issue, just letting you know that I would appreciate having access to this plugin in the 2024.1 IDE version. I don't know what the roadmap is, just whenever you get around to it.

Thank you for all your work!

**Comment by obiwan87** [comment]
Thank you for reminding me. Usually upgrading to the newest version is as easy as changing the version number in a config file. The plugin will be supported by 2024.1.* as of version 0.3.1

**Comment by sunarch** [comment]
Great! Thank you.
