### ISSUE TITLE
Support for ols.json

### ISSUE THREAD

**Issue by MineBill** [obiwan87/odin-intellij#26]
This is similar to #25 but needs some extra thought.

A project can have custom collections such as `packages` and needs some way to let this plugin know about them. [OLS](https://github.com/DanielGavin/ols) accomplishes this with an [ols.json](https://github.com/MineBill/Engin3/blob/d5d88bbb90403976bde59cacc000710ac60cff3d/ols.json#L3-L8) file that is defined per-project. In that file, it is possible to describe a list of collections and their path (relative to that file), which makes OLS aware of them and can provide completions. In an ideal world, there would be an odin build system with a configuration file that all editor plugins could parse and figure out what collections are used for the project but sadly, we do not live in such a world. This plugin could come up with it's own project file that describes these collection but since it's ultimately a `map[string]string` and a lot of odin users and project already use OLS and have an `ols.json`, i don't think it would be a terrible idea to temporarily parse it to figure out the collections. Then, at later date, if an odin-build system emerges and is accepted by the community we could switch to that.

**Comment by obiwan87** [comment]
Your suggestion makes a lot of sense, I'll definitely look into how re-using the ols.json settings when opening a project folder with IDEA.

**Comment by obiwan87** [comment]
When opening a project that has an ols.json but not configured source directories, the plugin will prompt the user to auto-detect the roots. Auto-detecting will set the collection and source paths according to ols.json. 
Also a new action in the project view context menu has been added: "Import Ols config"
