### ISSUE TITLE
Code Completion: Prioritize suggestions

### ISSUE THREAD

**Issue by obiwan87** [obiwan87/odin-intellij#39]
TODO:
- Prioritize suggestions that respect the type constraints of the suggestion context
- When using core/base/vendor-packages, prioritize symbols based on statistical relevance (scrape Odin github projects)

**Comment by Dima-369** [comment]
> When using core/base/vendor-packages, prioritize symbols based on statistical relevance (scrape Odin github projects)

I wouldn't scrape. Every project probably has other prioritization depending on the context. It would be fine if the completions work on frequency. So, if I pick `foo`, it appears at the top (or near the top) the next time, and so on.

That way, every project (or globally) builds up this completion suggestion list depending on what the user really needs.

**Comment by obiwan87** [comment]
Added with 0.6.3.
