### ISSUE TITLE
Add support for the 'File Structure' popup

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#45]
Apparently, the plugin does not have any support for it so far.

It looks like this, and everything is quickly searchable. I would be amazing to see all structs and all procedures this way.

![CleanShot 2024-08-08 at 23 13 58@2x](https://github.com/user-attachments/assets/0e4f6bed-62e2-469e-bbbe-ae92fde71c3c)

**Comment by obiwan87** [comment]
Hi @Dima-369 The file structure popup is coming with the next release.

**Comment by obiwan87** [comment]
![image](https://github.com/user-attachments/assets/ec5a1b48-0ef2-47d8-b45b-06eafeb9268b)

**Comment by Dima-369** [comment]
> The file structure popup is coming with the next release.

Very nice, thanks!

**Comment by Dima-369** [comment]
I tested in `develop` and this works well!
