### ISSUE TITLE
Is it possible to change the behavior of the 'Extend Selection' action to properly consider quotes?

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#46]
I am very used to the `Extend Selection` action in other programming languages, but I notice how it behaves a tad off for Odin.

If the cursor is on the space in the string `a := "test string"`, expanding first selects `test` which is good, but the next invocation selects `"test string"` with the quotes. In pretty much all other languages, it first proceeds to select everything inside the string first. So, I would expect `test string` (without quotes).

This throws off my muscle memory a lot.

**Comment by obiwan87** [comment]
Hi @Dima-369 
Can you please check if the behaviour in the video matches your expectations?
On Windows, I use Ctrl+W to expand selection and Ctrl+Shift+W to shrink the selection. 

I've tested this on the upcoming version 0.5.0, which I hope to deploy today or in the coming days

https://github.com/user-attachments/assets/b3f91c36-89f1-4250-8d69-dda57ac6013f

**Comment by Dima-369** [comment]
> Can you please check if the behaviour in the video matches your expectations?

Yes, exactly! I am looking forward to 0.5.0 🙂

**Comment by Dima-369** [comment]
I tested the latest `develop` and there this does not work?

https://github.com/user-attachments/assets/4c101eda-55b3-4b3c-b979-4e86b03bd93a

**Comment by obiwan87** [comment]
Huh? That's weird! Is it the same for all string literals?

**Comment by Dima-369** [comment]
It works in the Scala plugin for `.scala` files, but there is no `.bnf` file for their syntax to check against, apparently. Maybe this is a quirk with the lexer implementation in IntelliJ?

**Comment by Dima-369** [comment]
I checked a Kotlin file (where this also works correctly) with `Show Editor Highlighter Tokens` enabled, and found that they treat the surrounding quotes as special tokens, which may help in fixing this? 

![CleanShot 2024-08-13 at 20 37 22@2x](https://github.com/user-attachments/assets/0357a0b6-b54b-46dd-9100-c6e5eed47c26)

I am very new to the `.bnf` files, I suppose `DQ_STRING_LITERAL='regexp:"[^"]*"'` may need changes for this?

**Comment by obiwan87** [comment]
Oh cool, good to know. This is a tough one though. It has to be done on Lexer basis, which is defined in Odin.flex. The fact the strings would not contain quotes anymore would also have a series of consequences in the grammar, which is defined in Odin.bnf.

However, I was just looking at the token structure of Java. There, they also don't have any special tokens for opening or closing quotes, but it still works. Hmmm, this might be a question for JetBrains.

![image](https://github.com/user-attachments/assets/3634ccf5-b171-4b45-8e1c-d0d6237f1a7d)


FYI: The token definitions in Odin.bnf are merely for the Preview-Tool that I used in the beginning. But the grammar grew a lot in complexity with custom rules and parsing states. What I want to say: the regexes in Odin.bnf are meaningless. They are not used to create the tokens. Rather the lexer is created from Odin.flex

**Comment by obiwan87** [comment]
Anyway, ChatGPT knows it all. There is class called "ExtendWordSelectionHandler" which one can use to change the behaviour of extend/shrink selection.

**Comment by Dima-369** [comment]
> Anyway, ChatGPT knows it all.

Hah, I also feel that way for the IntelliJ Plugin SDK stuff - googling anything about it is such a pain 😄 

And that's cool, so we can achieve that behavior!

**Comment by obiwan87** [comment]
A pain indeed my friend! The nice thing is that the JetBrains guys really answer when posting a question on their issue tracker.

**Comment by obiwan87** [comment]
Ok, I think we got it now. I added OdinStringSelectioner that should take care of selecting to just before the quotes. Just pushed :)

**Comment by Dima-369** [comment]
I tested and indeed, it works perfectly for `"` now! Thanks.

I would love it if raw string literals via **`** would also be supported 😉 

https://github.com/user-attachments/assets/875ce5fe-2bf5-45a9-95fc-8697010bd8f8

**Comment by obiwan87** [comment]
> I tested and indeed, it works perfectly for `"` now! Thanks.
> 
> I would love it if raw string literals via **`** would also be supported 😉
> 
>  CleanShot.2024-08-14.at.13.25.04.mp4

Ah yes, adding it. :)

**Comment by obiwan87** [comment]
Should be working now. I just publish the plugin to the JetBrains Marketplace. It will be accepted within 1-2 business days :) Thank you so much for helping with this release 

FYI: I changed the Java version to 21, so you might have to change the project SDK to 21.

**Comment by Dima-369** [comment]
> Should be working now.

I tested and it works great, thanks!

> Thank you so much for helping with this release

Thank you as well for the superfast fixes.

I am happy that this plugin has become even more useful now! 🙂

**Comment by obiwan87** [comment]
I think on the next release I will focus on contextually correct code completion and refactorings. It is a pleasure to work with you. Feel free to join anytime you want
