### ISSUE TITLE
Only insert closing/matching bracket when whitespace follows

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#54]
This is how it behaves in PhpStorm for TypeScript (and many other supported languages):

The close bracket is inserted only when whitespace/newline follows it (from my plain tests, but might be more complicated?)

https://github.com/user-attachments/assets/b6c91440-244e-492e-80ea-4fbbd2cb016c

Currently, with Odin, it always inserts the closing bracket:

https://github.com/user-attachments/assets/4249930d-b441-4f6c-9f80-8dbe3d128438

It would be really nice if it would behave the same, since it is often annoying when you try to wrap things in `string()` or just extend existing code. This also breaks years of my bracket insertion muscle memory every single time 😄

**Comment by Dima-369** [comment]
ChatGPT: `PairedBraceMatcher` or `TypedHandlerDelegate` might be used.

**Comment by Dima-369** [comment]
Ah, there is already `OdinBraceMatcher.java`. This just needs modifications.

**Comment by obiwan87** [comment]
Regarding ChatGPT: I created OdinGPT, that is primed to be an expert at IntelliJ plugins and Odin: https://chatgpt.com/g/g-3pk1l0QGw-odingpt :)
