### ISSUE TITLE
Allow to hide the 'No Odin SDK has been setup for this project' notification or only show it when an Odin file is opened

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#61]
Since, it is always shown, even when I am in a Java or Kotlin repository without a single Odin file.

![CleanShot 2024-08-15 at 21 45 23@2x](https://github.com/user-attachments/assets/87b88257-309b-4d0c-9a9a-a323994b66a2)

**Comment by obiwan87** [comment]
ahh shit, ok, got ya

**Comment by obiwan87** [comment]
Ok, it was a one-liner. It's fixed ;-)

**Comment by Dima-369** [comment]
Tested and works! Thanks.
