### ISSUE TITLE
Idea: Allow 'Goto declaration' when triggered on the import string to show the directory the package is in?

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#62]
Very minor thing.

I realized that triggering 'Goto declaration' on the `import` statement shows all usages of the package, which is amazing! I then tried it on the string after and no information was given, so I thought if maybe the directory to the package could be shown in that tooltip? Or just jumping to the first source file in the package?

![CleanShot 2024-08-16 at 08 16 59@2x](https://github.com/user-attachments/assets/0f5d54a0-7fbf-4709-84a6-0aef227b995d)

**Comment by obiwan87** [comment]
With no alias it only works with the beginning of the import statement. I couldn't find a way to tie a string literal to a declaration yet

**Comment by obiwan87** [comment]
Ok, after some research I think I figured out the best practice:

- Aliases always find the usages within the file
- The path part opens the directory of the package in the project view
- If the path is outside the project, then it has to be added as external library in order for the "open directory" feature to work

In order for this to work, first, we have to add the SDK path as external library 

https://plugins.jetbrains.com/docs/intellij/workspace-model.html

**Comment by obiwan87** [comment]
This features has been implemented as described above :)

**Comment by Dima-369** [comment]
> This features has been implemented as described above :)

Nice, works well!
