### ISSUE TITLE
Show any kind of error when the Path to SDK is incorrectly set

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#63]
I accidentally pasted in a wrong path there, and then wondered why 'Goto declaration' and 'odin check' wasn't working anymore, until I realized the messed up path.

How about showing an error notification like 'Odin SDK path seems incorrect'? Maybe trigger it when the binary to `odin` isn't found or the `core` or `base` folders?

**Comment by obiwan87** [comment]
The SDK Path field is now validated in the project settings. Additionally, when the path is set correcltly, the odin version displayed under the SDK Path field
