### ISSUE TITLE
Fix reformatting issues with comments and imports

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#64]
## 1. Too many newlines inserted without any import statements (presumably where the imports would be)

```odin
package main

main :: proc() {
	
}
```

reformats to:

```odin
package main



main :: proc() {

}
```

## 2. Comments to a proc are indented incorrectly with too much prefix

 ```odin
package main

...

// hey there
// foo
main :: proc() {

}
```

results in:

```odin
    // hey there
    // foo
main :: proc() {

}
```

You can try to reformat `/opt/homebrew/Cellar/odin/2024-07/libexec/core/fmt/fmt_os.odin` which ends up like this with all the indentation being off:

```odin
  //+build !freestanding
    //+build !js
    //+build !orca
  package fmt

  import "base:runtime"
  import "core:bufio"
  import "core:io"
  import "core:os"
    // fprint formats using the default print settings and writes to fd
  fprint :: proc(fd: os.Handle, args: ..any, sep := " ", flush := true) -> int {
    buf: [1024]byte
    b: bufio.Writer
    defer bufio.writer_flush(&b)

    bufio.writer_init_with_buf(&b, os.stream_from_handle(fd), buf[:])
    w := bufio.writer_to_writer(&b)
    return wprint(w, ..args, sep=sep, flush=flush)
  }

    // fprintln formats using the default print settings and writes to fd
  fprintln :: proc(fd: os.Handle, args: ..any, sep := " ", flush := true) -> int {
```

**Comment by obiwan87** [comment]
I have now removed comment indentation. But now the problem should be that comments inside blocks are not indented inside blocks. E.g: 

Put a comment inside a procedure block and reformat. The comment will not be indented.

**Comment by obiwan87** [comment]
Blank lines after optimizing imports and/or reformatting code is now fixed

**Comment by Dima-369** [comment]
Here is still one weird case:

Before:

```odin
package main

import "core:os"

// oeu
foo :: proc() {
    os.exit(1)
}

// foo
main :: proc() {
}
```

After, the comment to the first `proc` under the imports always shifts up:

```odin
package main

import "core:os"
// oeu

foo :: proc() {
    os.exit(1)
}

// foo
main :: proc() {
}
```
