### ISSUE TITLE
Compiler Options not split as individual arguments

### ISSUE THREAD

**Issue by xraxra** [obiwan87/odin-intellij#76]
If I add the Compiler options to the build target: -strict-style -vet -no-bounds-check -o:speed -subsystem:windows

the build fails to run with: 

D:/dev/Odin/odin.exe run D:/dev/testing "-strict-style -vet -no-bounds-check -o:speed" -out:D:/dev/testing/bin/testing.exe
Unknown flag: 'strict-style -vet -no-bounds-check -o'

I'd expect the string to be split by the spaces, it looks like in OdinSdkUtils.java the whole string is added as addCommandPart

**Comment by obiwan87** [comment]
There you go: https://github.com/obiwan87/odin-intellij/releases/tag/v0.7.2

Download the zip and add choose "Install Plugin from Disk" from the action menu.
