### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by mibitzi** [obiwan87/odin-intellij#78]
When using themes such as Catppuccin the syntax highlighting incorrectly identifies code elements as `Identifier/Default` instead of e.g. `Identifier/Local variable` which leads to unintended highlighting.

This happens in Rider as well as CLion.

![image](https://github.com/user-attachments/assets/90879987-faa9-4cc5-948f-f3402ccb5c55)

As reference, here the same theme from the same author (Catppuccin Mocha) in neovim:

![image](https://github.com/user-attachments/assets/0632736e-19c9-46e8-8d0b-e4ce9aaae326)

**Comment by obiwan87** [comment]
Fix Is pushed. Added also fields, globals, params, and some more
