### ISSUE TITLE
Import package from suggestion adds unwanted spaces and brakes file

### ISSUE THREAD

**Issue by xabblll** [obiwan87/odin-intellij#79]
When I accept suggestion to add function or type from package which is not already imported in file, some space characters inserted in whole file.

This happens with different packages in large enough file

**demo**
<img width="400" alt="Screenshot 2024-10-30 at 23 20 28" src="https://github.com/user-attachments/assets/ad9e36d3-22ff-4925-b7af-3cc7817c79b1">
<img width="400" alt="Screenshot 2024-10-30 at 23 20 37" src="https://github.com/user-attachments/assets/cc22d1e0-6c26-4a33-baaa-a97b70e1ecee">
<img width="400" alt="Screenshot 2024-10-30 at 23 20 45" src="https://github.com/user-attachments/assets/475cd5e7-fe5c-4dd3-a200-a0ec4d05c503">

**Code from demo**

```Odin
package src

foo :: proc()
 {
    test := bui
}

TestFunc::proc() -> [2]f32
{
    vec :[2]f32: 32
    return [2]f32{vec.x, vec.y}  
}
```

Rider 2024.7
MacOS 14.3 (Apple Silicon)
Plugin version: 0.7.3 (installed from Rider plugin browser)

**Comment by obiwan87** [comment]
Was able to reproduce. For some reason, happens when both opening braces are after a new line. Probably has something to do with the synthetic End-Of-Statement token

**Comment by obiwan87** [comment]
Fixed
