### ISSUE TITLE
Define Code Style Settings page

### ISSUE THREAD

**Issue by obiwan87** [obiwan87/odin-intellij#9]

**Comment by obiwan87** [comment]
We need a special color for stuff like "dynamic" and "make"

**Comment by Dima-369** [comment]
How about just relying on `odinfmt.json`? See https://github.com/DanielGavin/ols

Or do you want to copy those settings into the Code Style?

**Comment by obiwan87** [comment]
Can use those values as default even though I'm a decent human being who uses "spaces" 😃
