### ISSUE TITLE
No IntelliSense on Vendor packages

### ISSUE THREAD

**Issue by TomasBorquez** [obiwan87/odin-intellij#97]
I get good colors on core libraries, but when using vendor, specifically on raylib, I get almost no intellisense:

![image](https://github.com/user-attachments/assets/eafb6d3e-e6f6-4e08-87b2-4792b2564e68)

These are my configs:

![image](https://github.com/user-attachments/assets/414a0ead-1e02-4318-9f43-e9a5b0dacacb)

And I have also set the main src folder as Sources Root:

![image](https://github.com/user-attachments/assets/2b61b1b4-b937-4ad3-b530-0b541d31aa1a)

For some reason I only get intellisense for raymath:

![image](https://github.com/user-attachments/assets/833d8983-61fc-413a-be55-c1b6e47697e8)

I'm using CLion 2024.3.1, tell me if I'm doing something stupid or if it is supposed to work like this, thank you :)

**Comment by TomasBorquez** [comment]
Its probably related to these errors:

![image](https://github.com/user-attachments/assets/9bd463fc-22e9-4223-bb43-1258a8df45fb)

![image](https://github.com/user-attachments/assets/55c69bbf-38ad-433c-9f15-051eda66cc0d)

Which i get both from `raygui.odin` and `raylib.odin`, and I have no errors on `raymath.odin`, is it because of my SDK version? Should I use an older version?

**Comment by Nesquick0** [comment]
I have same issue in Rider and RustRover with plugin 0.7.5. With 0.7.4 plugin version it works fine.

**Comment by TomasBorquez** [comment]
> I have same issue in Rider and RustRover with plugin 0.7.5. With 0.7.4 plugin version it works fine.

@Nesquick0 ah I see, how can I download an older version of the plugin?

**Comment by Nesquick0** [comment]
I think here in releases: https://github.com/obiwan87/odin-intellij/releases download odin-intellij-0.7.4.zip . No need to unpack.
And for me in Rider plugins window there is cog icon and install plugin from disk and select that odin-intellij-0.7.4.zip file.

**Comment by TomasBorquez** [comment]
> I think here in releases: https://github.com/obiwan87/odin-intellij/releases download odin-intellij-0.7.4.zip . No need to unpack. And for me in Rider plugins window there is cog icon and install plugin from disk and select that odin-intellij-0.7.4.zip file.

Yup 0.7.4 works correctly, thank you!

**Comment by obiwan87** [comment]
Oops!! ^^
@TomasBorquez Thank you for reporting it! Will fix with the next release
