### ISSUE TITLE
"Odin Collection Root" hides contents of folder

### ISSUE THREAD

**Issue by DuchGhast** [obiwan87/odin-intellij#98]
Folder marked as "Odin Collection Root" does not show any contents when expanded. When folder is unmarked then folder returns to normal state.

**Comment by obiwan87** [comment]
Could you please specify what IDE and what version of the plugin you are using?

**Comment by DuchGhast** [comment]
Plugin 0.8.0
IntelliJ IDEA 2024.3.1.1 (Ultimate Edition) | (2024.3.1 has the same issue)

**Comment by obiwan87** [comment]
I found a workaround. Please disable "Compact Middle Packages" in the project view settings (see screenshot):

![image](https://github.com/user-attachments/assets/e54a8a11-69c4-4227-a43c-63b9df94ad99)

**Comment by obiwan87** [comment]
Deactivated the compact middle packages setting for collection directories. It's a workaround, but couldn't find a better way for now.
